In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("movies.csv")

In [3]:
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English

In [4]:
df.shape

(37, 10)

In [5]:
df.columns

Index(['title', 'industry', 'release_year', 'imdb_rating', 'studio', 'budget',
       'revenue', 'unit', 'currency', 'language'],
      dtype='str')

In [8]:
df.industry.unique()

<StringArray>
['Bollywood', 'Hollywood']
Length: 2, dtype: str

In [9]:
type(df.industry)

pandas.Series

In [11]:
df.language.unique()

<StringArray>
['Bengali', 'English', 'Hindi', 'Kannada', 'Telugu']
Length: 5, dtype: str

In [14]:
df["language"].unique()

<StringArray>
['Bengali', 'English', 'Hindi', 'Kannada', 'Telugu']
Length: 5, dtype: str

In [15]:
df.industry.value_counts()

industry
Hollywood    20
Bollywood    17
Name: count, dtype: int64

In [16]:
df.language.value_counts()

language
English    20
Hindi      12
Telugu      3
Bengali     1
Kannada     1
Name: count, dtype: int64

In [18]:
df_new = df[['title', 'industry', 'release_year', 'imdb_rating']]

In [19]:
df_new

,title,industry,release_year,imdb_rating
0,Pather Panchali,Bollywood,1955,8.3
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0
2,Thor: The Dark World,Hollywood,2013,6.8
3,Thor: Ragnarok,Hollywood,2017,7.9
4,Thor: Love and Thunder,Hollywood,2022,6.8
5,The Shawshank Redemption,Hollywood,1994,9.3
6,Interstellar,Hollywood,2014,8.6
7,The Pursuit of Happyness,Hollywood,2006,8.0
8,Gladiator,Hollywood,2000,8.5
9,Titanic,Hollywood,1997,7.9
10,It's a Wonderful Life,Hollywood,1946,8.6
11,Avatar,Hollywood,2009,7.8
12,The Godfather,Hollywood,1972,9.2
13,The Dark Knight,Hollywood,2008,9.0
14,Schindler's List,Hollywood,1993,9.0
15,Jurassic Park,Hollywood,1993,8.2
16,Parasite,Hollywood,2019,8.5
17,Avengers: Endgame,Hollywood,2019,8.4
18,Avengers: Infinity War,Hollywood,2018,8.4
19,Captain America: The First Avenger,Hollywood,2011,6.9
20,Captain America: The Winter Soldier,Hollywood,2014,7.8
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0
22,3 Idiots,Bollywood,2009,8.4
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4
24,Bajirao Mastani,Bollywood,2015,7.2
25,Taare Zameen Par,Bollywood,2007,8.3
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1
27,PK,Bollywood,2014,8.1
28,Sanju,Bollywood,2018,NaN
29,The Kashmir Files,Bollywood,2022,8.3
30,Bajrangi Bhaijaan,Bollywood,2015,8.1
31,Race 3,Bollywood,2018,1.9
32,Shershaah,Bollywood,2021,8.4
33,K.G.F: Chapter 2,Bollywood,2022,8.4
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6
35,RRR,Bollywood,2022,8.0
36,Baahubali: The Beginning,Bollywood,2015,8.0

In [20]:
df[(df.release_year>=2000) & (df.release_year<=2010)]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.0,307.1,Millions,USD,English
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.0,460.5,Millions,USD,English
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.0,2847.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.0,1006.0,Millions,USD,English
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.0,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.0,1360.0,Millions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.0,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.0,410.0,Millions,INR,Hindi

In [22]:
df[df.studio == "Marvel Studios"]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.0,2798.0,Millions,USD,English
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.0,2048.0,Millions,USD,English
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.7,370.6,Millions,USD,English
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.0,714.4,Millions,USD,English

In [21]:
df.studio.unique()

<StringArray>
['Government of West Bengal',            'Marvel Studios',
 'Castle Rock Entertainment',     'Warner Bros. Pictures',
         'Columbia Pictures',      'Universal Pictures  ',
        'Paramount Pictures',             'Liberty Films',
          '20th Century Fox',                   'Syncopy',
        'Universal Pictures',                         nan,
            'Yash Raj Films',        'Vinod Chopra Films',
        'Dharma Productions',  'Vinod Chopra Productions',
               'Zee Studios',         'Salman Khan Films',
             'Hombale Films',       'Mythri Movie Makers',
         'DVV Entertainment',          'Arka Media Works']
Length: 22, dtype: str

In [24]:
df.describe()

       release_year  imdb_rating        budget        revenue
count     37.000000    36.000000     37.000000      37.000000
mean    2007.027027     7.919444   2084.975135    4117.135135
std       17.657995     1.204947  11477.487145   16372.462682
min     1946.000000     1.900000      1.000000       3.100000
25%     2001.000000     7.800000     15.500000     263.100000
50%     2014.000000     8.100000    165.000000     701.800000
75%     2018.000000     8.400000    250.000000    2000.000000
max     2022.000000     9.300000  70000.000000  100000.000000

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         37 non-null     str
 1   industry      37 non-null     str
 2   release_year  37 non-null     int64
 3   imdb_rating   36 non-null     float64
 4   studio        34 non-null     str
 5   budget        37 non-null     float64
 6   revenue       37 non-null     float64
 7   unit          37 non-null     str
 8   currency      37 non-null     str
 9   language      37 non-null     str
dtypes: float64(3), int64(1), str(6)
memory usage: 3.0 KB

In [26]:
df.imdb_rating.max()

np.float64(9.3)

In [31]:
df[(df.imdb_rating == df.imdb_rating.max()) | (df.imdb_rating == df.imdb_rating.min())]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.8,3.1,Billions,INR,Hindi

In [32]:
df["age"] = df.release_year.apply(lambda x : 2026 - x)
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,71
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,4
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,9
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,4

In [33]:
df["profit"] = df["revenue"] - df["budget"]
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,71,30000.0
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,4,754.8
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13,479.8
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,9,674.0
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,4,420.0

In [41]:
df["profit"] = df.apply(lambda x : x.revenue - x.budget, axis=1)
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,71,30000.0
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,4,754.8
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13,479.8
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,9,674.0
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,4,420.0

In [46]:
df.index

RangeIndex(start=0, stop=37, step=1)

In [47]:
df.loc[2]

title           Thor: The Dark World
industry                    Hollywood
release_year                     2013
imdb_rating                       6.8
studio                 Marvel Studios
budget                          165.0
revenue                         644.8
unit                         Millions
currency                          USD
language                      English
age                                13
profit                          479.8
Name: 2, dtype: object

In [48]:
df.iloc[3]

title           Thor: Ragnarok
industry              Hollywood
release_year               2017
imdb_rating                 7.9
studio           Marvel Studios
budget                    180.0
revenue                   854.0
unit                   Millions
currency                    USD
language                English
age                           9
profit                    674.0
Name: 3, dtype: object

In [45]:
df.loc[[2,3]]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13,479.8
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,9,674.0

In [50]:
df.set_index('title', inplace=True)

In [51]:
df.head()

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
title,,,,,,,,,,,
Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,71,30000.0
Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,4,754.8
Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13,479.8
Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,9,674.0
Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,4,420.0

In [55]:
df.loc['Pather Panchali']

industry                        Bollywood
release_year                         1955
imdb_rating                           8.3
studio          Government of West Bengal
budget                            70000.0
revenue                          100000.0
unit                            Thousands
currency                              INR
language                          Bengali
age                                    71
profit                            30000.0
Name: Pather Panchali, dtype: object

In [59]:
df.loc[['Pather Panchali', "Doctor Strange in the Multiverse of Madness"]]

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
title,,,,,,,,,,,
Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,71,30000.0
Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,4,754.8

In [60]:
df.iloc[4:9]

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
title,,,,,,,,,,,
Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,4,420.0
The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English,32,48.3
Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.0,701.8,Millions,USD,English,12,536.8
The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.0,307.1,Millions,USD,English,20,252.1
Gladiator,Hollywood,2000,8.5,Universal Pictures,103.0,460.5,Millions,USD,English,26,357.5