In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("stock_data.csv")
df.head()
# row 0 is actually a header

,Datasource: Google finance,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,tickers,eps,revenue,price,people
1,GOOGL,27.82,87,845,larry page
2,WMT,4.61,484,65,n.a.
3,MSFT,-1,85,64,bill gates
4,RIL,not available,50,1023,mukesh ambani

In [3]:
df = pd.read_csv("stock_data.csv", skiprows=1)
df.head()
# Skip rows skips row 1 from data and automatically promoted that row to column name

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [4]:
df = pd.read_csv("stock_data.csv", skiprows=2)
df.head()
# Skip rows skips row 1 from data and automatically promoted 2nd row to column name

  GOOGL          27.82   87   845     larry page
0   WMT           4.61  484    65           n.a.
1  MSFT             -1   85    64     bill gates
2  RIL   not available   50  1023  mukesh ambani
3  TATA            5.6   -1  n.a.     ratan tata

In [5]:
df = pd.read_csv("stock_data.csv", header=1)
df.head()

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [6]:
df = pd.read_csv("stock_data.csv", header=1, names=["stock_symbol", "eps", "revenue", "price", "people"])
df.head()

  stock_symbol            eps  revenue price         people
0        GOOGL          27.82       87   845     larry page
1          WMT           4.61      484    65           n.a.
2         MSFT             -1       85    64     bill gates
3         RIL   not available       50  1023  mukesh ambani
4         TATA            5.6       -1  n.a.     ratan tata

In [7]:
df = pd.read_csv("stock_data.csv", header=1, names=["stock_symbol", "eps", "revenue", "price", "people"], nrows=5)
df.head()

  stock_symbol            eps  revenue price         people
0        GOOGL          27.82       87   845     larry page
1          WMT           4.61      484    65           n.a.
2         MSFT             -1       85    64     bill gates
3         RIL   not available       50  1023  mukesh ambani
4         TATA            5.6       -1  n.a.     ratan tata

In [8]:
df = pd.read_csv("stock_data.csv", header=1, na_values={
    'eps' : ['not available', -1],
    'revenue' : [-1],
    'price': ['n.a.'],
    'people': ['n.a.'],
})
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT    NaN     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [9]:
df = pd.read_csv("stock_data.csv", header=1, na_values=['not available', -1, 'n.a.'])
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT    NaN     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [10]:
df['pe'] = df['price']/df['eps']
df

  tickers    eps  revenue   price         people         pe
0   GOOGL  27.82     87.0   845.0     larry page  30.373832
1     WMT   4.61    484.0    65.0            NaN  14.099783
2    MSFT    NaN     85.0    64.0     bill gates        NaN
3    RIL     NaN     50.0  1023.0  mukesh ambani        NaN
4    TATA   5.60      NaN     NaN     ratan tata        NaN

In [11]:
df.to_csv("pe.csv")

In [12]:
df.to_csv("pe1.csv", index=False, header=False)

In [13]:
pip install openpyxl

Requirement already satisfied: openpyxl in /opt/homebrew/Cellar/jupyterlab/4.6.1/libexec/lib/python3.14/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /opt/homebrew/Cellar/jupyterlab/4.6.1/libexec/lib/python3.14/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [16]:
df_movies=pd.read_excel("movies_db.xlsx", "movies")
df_movies

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5
5,106,Sholay,Bollywood,1975,8.1,United Producers,1
6,107,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,1
7,108,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,1
8,109,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,1
9,110,Bajirao Mastani,Bollywood,2015,7.2,NaN,1
10,111,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,5
11,112,Inception,Hollywood,2010,8.8,Warner Bros. Pictures,5
12,113,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,5
13,115,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,5
14,116,Gladiator,Hollywood,2000,8.5,Universal Pictures,5
15,117,Titanic,Hollywood,1997,7.9,Paramount Pictures,5
16,118,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,5
17,119,Avatar,Hollywood,2009,7.8,20th Century Fox,5
18,120,The Godfather,Hollywood,1972,9.2,Paramount Pictures,5
19,121,The Dark Knight,Hollywood,2008,9.0,Syncopy,5
20,122,Schindler's List,Hollywood,1993,9.0,Universal Pictures,5
21,123,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,5
22,124,Parasite,Hollywood,2019,8.5,NaN,5
23,125,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,5
24,126,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,5
25,127,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,7
26,128,Taare Zameen Par,Bollywood,2007,8.3,NaN,1
27,129,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,1
28,130,PK,Bollywood,2014,8.1,Vinod Chopra Films,1
29,131,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1
30,132,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2
31,133,RRR,Bollywood,2022,8.0,DVV Entertainment,2
32,134,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,2
33,135,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,1
34,136,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,1
35,137,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,5
36,138,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,5
37,139,Race 3,Bollywood,2018,1.9,Salman Khan Films,1
38,140,Shershaah,Bollywood,2021,8.4,Dharma Productions,1

In [17]:
df_movies.columns

Index(['movie_id', 'title', 'industry', 'release_year', 'imdb_rating',
       'studio', 'language_id'],
      dtype='str')

In [20]:
def standerdize_currency(curr):
    if curr == "$$" or curr == "Dollars":
        return "USD"
    return curr

df_financials=pd.read_excel("movies_db.xlsx", "financials", converters={
    'currency':standerdize_currency
})
df_financials.head()

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions      USD
3       104   180.0    854.0  Millions      USD
4       105   250.0    670.0  Millions      USD

In [21]:
df_merged = pd.merge(df_movies, df_financials, on = "movie_id")
df_merged.head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,1.0,12.5,Billions,INR
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,200.0,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,165.0,644.8,Millions,USD
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,180.0,854.0,Millions,USD
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5,250.0,670.0,Millions,USD

In [23]:
df_merged.to_excel("movies_merged.xlsx",sheet_name="merged_financials", index=False)