In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("weather_data.csv")
df.head()

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/4/2017          NaN        9.0  Sunny
2  1/5/2017         28.0        NaN   Snow
3  1/6/2017          NaN        7.0    NaN
4  1/7/2017         32.0        NaN   Rain

In [3]:
df.dtypes

day                str
temperature    float64
windspeed      float64
event              str
dtype: object

In [4]:
df = pd.read_csv("weather_data.csv", parse_dates=["day"])
df.head()

         day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-04          NaN        9.0  Sunny
2 2017-01-05         28.0        NaN   Snow
3 2017-01-06          NaN        7.0    NaN
4 2017-01-07         32.0        NaN   Rain

In [5]:
df.dtypes

day            datetime64[us]
temperature           float64
windspeed             float64
event                     str
dtype: object

In [6]:
df.set_index('day', inplace=True)
df.head()

            temperature  windspeed  event
day
2017-01-01         32.0        6.0   Rain
2017-01-04          NaN        9.0  Sunny
2017-01-05         28.0        NaN   Snow
2017-01-06          NaN        7.0    NaN
2017-01-07         32.0        NaN   Rain

In [7]:
df.fillna(0)

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          0.0        9.0   Sunny
2017-01-05         28.0        0.0    Snow
2017-01-06          0.0        7.0       0
2017-01-07         32.0        0.0    Rain
2017-01-08          0.0        0.0   Sunny
2017-01-09          0.0        0.0       0
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [8]:
df.fillna({
    'temperature':df.temperature.median(),
    'windspeed': df.windspeed.mean(),
    'event':'No Event'
})

            temperature  windspeed     event
day
2017-01-01         32.0       6.00      Rain
2017-01-04         32.0       9.00     Sunny
2017-01-05         28.0       8.42      Snow
2017-01-06         32.0       7.00  No Event
2017-01-07         32.0       8.42      Rain
2017-01-08         32.0       8.42     Sunny
2017-01-09         32.0       8.42  No Event
2017-01-10         34.1       8.10    Cloudy
2017-01-11         40.0      12.00     Sunny

In [9]:
df.ffill()

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        7.0   Sunny
2017-01-09         32.0        7.0   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [10]:
df.bfill()

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         28.0        9.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         32.0        7.0    Rain
2017-01-07         32.0        8.1    Rain
2017-01-08         34.1        8.1   Sunny
2017-01-09         34.1        8.1  Cloudy
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [11]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [12]:
df.ffill(axis='columns')

           temperature windspeed   event
day
2017-01-01        32.0       6.0    Rain
2017-01-04         NaN       9.0   Sunny
2017-01-05        28.0      28.0    Snow
2017-01-06         NaN       7.0     7.0
2017-01-07        32.0      32.0    Rain
2017-01-08         NaN       NaN   Sunny
2017-01-09         NaN       NaN     NaN
2017-01-10        34.1       8.1  Cloudy
2017-01-11        40.0      12.0   Sunny

In [13]:
df.bfill(axis='columns')

           temperature windspeed   event
day
2017-01-01        32.0       6.0    Rain
2017-01-04         9.0       9.0   Sunny
2017-01-05        28.0      Snow    Snow
2017-01-06         7.0       7.0     NaN
2017-01-07        32.0      Rain    Rain
2017-01-08       Sunny     Sunny   Sunny
2017-01-09         NaN       NaN     NaN
2017-01-10        34.1       8.1  Cloudy
2017-01-11        40.0      12.0   Sunny

In [14]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [15]:
df['temperature'] = df['temperature'].interpolate()
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         30.0        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06         30.0        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08         32.7        NaN   Sunny
2017-01-09         33.4        NaN     NaN
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [16]:
df = pd.read_csv("weather_data.csv", parse_dates=["day"])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [17]:
df.dropna(how="all")

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [18]:
df.dropna(thresh=2)

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

## Part 2

In [20]:
df=pd.read_csv("weather_data_999.csv")
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [21]:
import numpy as np

In [22]:
df.replace(-99999, np.nan)

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0   -88888.0  no event

In [23]:
df.replace([-99999,-88888], np.nan)

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0        NaN  no event

In [24]:
df.replace(to_replace=[-99999,-88888], value=np.nan)

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0        NaN  no event

In [25]:
df.replace({
    'temperature':-99999,
    'windspeed':[-88888,-99999],
    'event':'no event'
}, np.nan)

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        NaN    NaN

In [26]:
df.replace({
    -99999:np.nan,
    -88888:np.nan,
    'no event' : 'Sunny'})

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0  Sunny
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        NaN  Sunny

In [27]:
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [29]:
df.replace([-99999,-88888,'no event'], [np.nan, 0, 'Moderate'])

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  Moderate
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0        0.0  Moderate