In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("weather_by_cities.csv")
df

         day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [3]:
df["city"]=="new york"

0      True
1      True
2      True
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
Name: city, dtype: bool

In [4]:
df[df["city"]=="new york"]

        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny

In [5]:
g=df.groupby('city')

In [6]:
g

In [7]:
for city, data in g:
    print("city:", city)
    print("\ndata:", data)

city: mumbai

data:         day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
city: new york

data:         day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
city: paris

data:          day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

In [8]:
for city, data in g:
    print("city:", city)
    print("data:", data.temperature.max())

city: mumbai
data: 92
city: new york
data: 36
city: paris
data: 54

In [9]:
g.get_group('paris')

         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

In [10]:
g.max()

               day  temperature  windspeed  event
city
mumbai    1/4/2017           92         15  Sunny
new york  1/4/2017           36         12  Sunny
paris     1/4/2017           54         20  Sunny

In [11]:
g.min()

               day  temperature  windspeed   event
city
mumbai    1/1/2017           85          5     Fog
new york  1/1/2017           28          6    Rain
paris     1/1/2017           42          8  Cloudy

In [12]:
g.describe()

         temperature                                                   \
               count   mean       std   min    25%   50%    75%   max
city
mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0

         windspeed
             count   mean       std  min   25%   50%    75%   max
city
mumbai         4.0   9.25  5.057997  5.0  5.00   8.5  12.75  15.0
new york       4.0   8.00  2.708013  6.0  6.75   7.0   8.25  12.0
paris          4.0  12.75  5.251984  8.0  9.50  11.5  14.75  20.0

In [13]:
g.size()

city
mumbai      4
new york    4
paris       4
dtype: int64

In [14]:
def group_function(df, idx, col):
    if 70<=df[col].loc[idx]<=90:
        return "70-90"
    elif 50<=df[col].loc[idx]<=70:
        return "50-70"
    else:
        return "others"

In [15]:
g=df.groupby(lambda idx : group_function(df, idx, 'temperature'))
g

In [16]:
for key, data in g:
    print("\nkey:", key)
    print("data:", data)

key: 50-70
data:          day   city  temperature  windspeed   event
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy

key: 70-90
data:         day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog

key: others
data:          day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
11  1/4/2017     paris           42         10  Cloudy

In [17]:
df.groupby('city')['temperature'].mean()

city
mumbai      88.50
new york    32.25
paris       47.75
Name: temperature, dtype: float64

In [18]:
df.groupby('day')['temperature'].max()

day
1/1/2017    90
1/2/2017    85
1/3/2017    87
1/4/2017    92
Name: temperature, dtype: int64

In [19]:
df.groupby(['city', 'event'])['temperature'].max()

city      event
mumbai    Fog       87
          Rain      92
          Sunny     90
new york  Rain      32
          Snow      28
          Sunny     36
paris     Cloudy    54
          Sunny     45
Name: temperature, dtype: int64

In [20]:
df.groupby('city').agg({
    'temperature': ['mean', 'max'],
    'windspeed': 'sum'
})

         temperature     windspeed
                mean max       sum
city
mumbai         88.50  92        37
new york       32.25  36        32
paris          47.75  54        51